//
//  HomeViewControllerProtocol.swift
//  MVVMCombine
//
//  Created by Mohamed ElSheikh on 31/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import UIKit

protocol HomeViewControllerProtocol: BaseViewController {
    var coordinator: HomeCoordinatorProtocol? { get set }
    var viewModel: HomeViewModelProtocol? { get set }
}
