//
//  HomeViewModelProtocol.swift
//  MVVMCombine
//
//  Created by Mohamed ElSheikh on 31/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Combine

protocol HomeViewModelProtocol: AnyObject {
    var newsObserver: PassthroughSubject<[NewsItem]?, Never> { get set }
    var loadingObserver: PassthroughSubject<Bool, Never> { get set }
    var networkErrorObserver: PassthroughSubject<String, Never> { get set }
    func getNews()
}
