//
//  DetailsViewController.swift
//  MVVMCombine
//
//  Created by Mohamed ElSheikh on 31/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Combine
import UIKit

class DetailsViewController: BaseViewController, DetailsViewControllerProtocol {
    var coordinator: DetailsCoordinatorProtocol?
    var viewModel: DetailsViewModelProtocol?
    private var cancellables = Set<AnyCancellable>()

    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        bindData()
    }

    deinit {
        AppCoordinator.shared.currentCoordinators.removeAll(where: { $0 == coordinator })
    }
}

private extension DetailsViewController {
    func setupUI() {
    }

    func bindData() {
        
    }
}
