//
//  DetailsCoordinator.swift
//  MVVMCombine
//
//  Created by Mohamed ElSheikh on 31/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects
//

import Combine
import UIKit

class DetailsCoordinator: BaseCoordinator, DetailsCoordinatorProtocol {
    weak var controller: DetailsViewControllerProtocol?
    var callBack: PassthroughSubject<DetailsCoordinatorCallback, Never>?
    var navigationController: UINavigationController?
    
    func start(model: DetailsCoordinatorModelProtocol,
                    callBack: PassthroughSubject<DetailsCoordinatorCallback, Never>) -> UIViewController {
        self.callBack = callBack
        navigationController = model.navigationController
        let viewModel = DetailsViewModel()
        viewModel.service = NewsServiceServices()
        let controller = DetailsViewController.loadFromNib()
        self.controller = controller
        controller.coordinator = self
        controller.viewModel = viewModel
        AppCoordinator.shared.currentCoordinators.append(self)
        return controller
    }

    deinit {
        callBack?.send(.closed)
    }
}
